const themes = {
  'forest-sage': {
    name: '森林绿',
    colors: {
      bgPrimary: '#F5F3EE',
      bgSidebar: '#EFF3EB',
      bgCard: '#FFFFFFEE',
      bgCardHover: '#FFFFFF',
      accent: '#2D5E3A',
      accentHover: '#3A7549',
      accentLight: '#E8F0E4',
      fgPrimary: '#1B3A28',
      fgSecondary: '#4A6B52',
      fgMuted: '#7A9A80',
      border: '#D6DDD0',
      borderMedium: '#B8C5B0',
      overdue: '#D4483B',
      important: '#D49B3B',
      complete: '#3D9B5E',
    },
    antd: {
      colorPrimary: '#2D5E3A',
      colorBgContainer: '#FFFFFF',
      colorBgLayout: '#F5F3EE',
      colorBorder: '#D6DDD0',
      colorBorderSecondary: '#E8F0E4',
      colorText: '#1B3A28',
      colorTextSecondary: '#4A6B52',
      colorTextTertiary: '#7A9A80',
    },
  },
  'warm-linen': {
    name: '暖亚麻',
    colors: {
      bgPrimary: '#F3EBE2',
      bgSidebar: '#EAE3DB',
      bgCard: '#FDFAF8EE',
      bgCardHover: '#FDFAF8',
      accent: '#D4916E',
      accentHover: '#E0A47E',
      accentLight: '#F5E6DC',
      fgPrimary: '#1A1A1A',
      fgSecondary: '#3D3D3D',
      fgMuted: '#6B6B6B',
      border: '#DDD8D3',
      borderMedium: '#C5BEB6',
      overdue: '#C94B3F',
      important: '#D49B3B',
      complete: '#5B9A6F',
    },
    antd: {
      colorPrimary: '#D4916E',
      colorBgContainer: '#FDFAF8',
      colorBgLayout: '#F3EBE2',
      colorBorder: '#DDD8D3',
      colorBorderSecondary: '#EAE3DB',
      colorText: '#1A1A1A',
      colorTextSecondary: '#3D3D3D',
      colorTextTertiary: '#6B6B6B',
    },
  },
  'lavender-mist': {
    name: '薰衣紫',
    colors: {
      bgPrimary: '#F3EFF8',
      bgSidebar: '#EBE5F3',
      bgCard: '#FBF9FEEE',
      bgCardHover: '#FBF9FE',
      accent: '#8B5CF6',
      accentHover: '#9D6FF8',
      accentLight: '#EDE9FE',
      fgPrimary: '#1A1A1A',
      fgSecondary: '#555555',
      fgMuted: '#A3A3A3',
      border: '#DDD6EA',
      borderMedium: '#CFC3E2',
      overdue: '#F87171',
      important: '#FBBF24',
      complete: '#34D399',
    },
    antd: {
      colorPrimary: '#8B5CF6',
      colorBgContainer: '#FBF9FE',
      colorBgLayout: '#F3EFF8',
      colorBorder: '#DDD6EA',
      colorBorderSecondary: '#EBE5F3',
      colorText: '#1A1A1A',
      colorTextSecondary: '#555555',
      colorTextTertiary: '#A3A3A3',
    },
  },
  'minimal-ink': {
    name: '极简墨',
    colors: {
      bgPrimary: '#FFFFFF',
      bgSidebar: '#FAFAFA',
      bgCard: '#FFFFFFEE',
      bgCardHover: '#FFFFFF',
      accent: '#0066FF',
      accentHover: '#3385FF',
      accentLight: '#E6F0FF',
      fgPrimary: '#1A1A1A',
      fgSecondary: '#666666',
      fgMuted: '#999999',
      border: '#EAEAEA',
      borderMedium: '#D4D4D4',
      overdue: '#EF4444',
      important: '#EAB308',
      complete: '#22C55E',
    },
    antd: {
      colorPrimary: '#0066FF',
      colorBgContainer: '#FFFFFF',
      colorBgLayout: '#FFFFFF',
      colorBorder: '#EAEAEA',
      colorBorderSecondary: '#F0F0F0',
      colorText: '#1A1A1A',
      colorTextSecondary: '#666666',
      colorTextTertiary: '#999999',
    },
  },
};

export const themeKeys = Object.keys(themes);
export default themes;
